sudo: required
dist: trusty
language: go

go:
  - 1.12.x

script:
  - export TAG=${TRAVIS_BRANCH} 
  - make all check container &&
    if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}";
      make deploy;
    fi
notifications:
  email:
    on_success: always
    on_failure: always




